PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select * where {
    ?s rdf:type <http://example.org/csv/MeanEarningRecord> .
    ?s <http://dbpedia.org/ontology/censusYear> "2018" .
    ?s <http://dbpedia.org/ontology/county> ?c .
    ?s <http://dbpedia.org/ontology/average> ?mean .
    
    ?bachelordegree <http://dbpedia.org/ontology/county> ?c .
    ?bachelordegree <http://dbpedia.org/ontology#censusYear> "2016" .
    ?bachelordegree <http://purl.org/dc/terms#educationLevel> "Ordinary bachelor degree/professional qualification or both" .
    ?bachelordegree <http://dbpedia.org/ontology/sex> "Both sexes".
    ?bachelordegree <http://rdf-vocabulary.ddialliance.org/discovery#frequency> ?bachelordegree_value
}
ORDER BY DESC(xsd:integer(?bachelordegree_value))
limit 10

