PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select (?c as ?countyName) (?mean as ?meanEarning) (?ageeduceased_value as ?ageEduCeased) where {
    ?s rdf:type <http://example.org/csv/MeanEarningRecord> .
    ?s <http://dbpedia.org/ontology/censusYear> "2018" .
    ?s <http://dbpedia.org/ontology/county> ?c .
    ?s <http://dbpedia.org/ontology/average> ?mean .
    
    ?ageeduceased <http://dbpedia.org/ontology/county> ?c .
    ?ageeduceased <http://dbpedia.org/ontology#censusYear> "2016" .
    ?ageeduceased <http://rdf-vocabulary.ddialliance.org/discovery#statisticsCategory> "Average_Age_Education_Ceased_(Number)".
    ?ageeduceased <http://rdf-vocabulary.ddialliance.org/discovery#frequency> ?ageeduceased_value
}
ORDER BY ASC(xsd:integer(?mean))
limit 10000

