PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select  (?c as ?CountyName) (?ageeduceased_value as ?AgeEducationCeased)  (SUM(xsd:integer(?degree_value)) as ?DegreeHolders) where {
    ?ageeduceased <http://dbpedia.org/ontology/county> ?c .
    ?ageeduceased <http://dbpedia.org/ontology#censusYear> "2016" .
    ?ageeduceased <http://rdf-vocabulary.ddialliance.org/discovery#statisticsCategory> "Average_Age_Education_Ceased_(Number)".
    ?ageeduceased <http://rdf-vocabulary.ddialliance.org/discovery#frequency> ?ageeduceased_value .
    
    ?bachelordegree <http://dbpedia.org/ontology/county> ?c .
    ?bachelordegree <http://dbpedia.org/ontology#censusYear> "2016" .
    
    ?bachelordegree <http://purl.org/dc/terms#educationLevel>   ?degree.
            
    FILTER (
            ?degree in ("Ordinary bachelor degree/professional qualification or both","Honours bachelor degree/professional qualification or both","Postgraduate diploma or degree","Doctorate (Ph.D.)")
    )
    
    ?bachelordegree <http://dbpedia.org/ontology/sex> "Both sexes".
    ?bachelordegree <http://rdf-vocabulary.ddialliance.org/discovery#frequency> ?degree_value .
    ?bachelordegree <http://xmlns.com/foaf/0.1/#age> "Total persons" .
}
GROUP BY ?c ?mean ?ageeduceased_value
ORDER BY ASC(?degreeHolder_sum)
limit 10

