PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select  ?c ?mean  (SUM(xsd:integer(?nodegreesum))/SUM(xsd:integer(?degree_value)) as ?nodegree_perc) where {
    ?s rdf:type <http://example.org/csv/MeanEarningRecord> .
    ?s <http://dbpedia.org/ontology/censusYear> "2018" .
    ?s <http://dbpedia.org/ontology/county> ?c .
    ?s <http://dbpedia.org/ontology/average> ?mean .
    
    ?bachelordegree <http://dbpedia.org/ontology/county> ?c .
    ?bachelordegree <http://dbpedia.org/ontology#censusYear> "2016" .
    
    ?bachelordegree <http://purl.org/dc/terms#educationLevel>   ?degree.
    
    BIND ( IF(?degree in ("Doctorate (Ph.D.)"), ?degree_value, 0 ) as ?nodegreesum )
    
    ?bachelordegree <http://dbpedia.org/ontology/sex> "Both sexes".
    ?bachelordegree <http://rdf-vocabulary.ddialliance.org/discovery#frequency> ?degree_value
}
GROUP BY ?c ?mean
ORDER BY DESC(?nodegree_perc)
limit 10

